### ISSUE TITLE
Undefined function or variable 'r'.

### ISSUE THREAD

**Issue by JasonLo** [aojeda/mobilab#10]
Do you mean

`wts = wts*sph*U(:,sorting(1:end-(n-r)))';`

should be

`wts = wts*sph*U(:,sorting(1:end-(n-minRank)))';`

?

**Comment by aojeda** [comment]
Yes you are right. Thanks for pointing this out. I have fixed this bug in the development branch and I will merge it with the master as soon as I am done with other features I am working on.

Thanks!
